language: node_js
node_js:
- iojs
deploy:
  provider: npm
  email: jan.krems+quinnjs@gmail.com
  api_key:
    secure: MycxCnN17jICkZT5p8PqmhkS20GChaA31ViKrIhjtfAWRW4uMLeuzCYvkZxUG1DVysU2MM1b7pjZ/o/Q+8hxZW/K3mpbk0q3S32PMJseeN0JcgKSbFUPs87CTaDJ4QRbwAm3+T7lUaWJkJxHsleq9CuVpacQiZ0Yz6HBg6DdUWu3VPiNvz0rYeFoqtg/2Hqm1Ndxc2v59ngrmdRHUFkDk96drGdfSIxpDe3YYu+xG0KA53Z9hJK/bNze49OmbxqgpvddBtMjDfhKD+lwOkFrLjQ/Q4X7fZkVUGCeLIu9f/sPMHMB6+JY/waNESXPm2Z38bM3f0x/0bFJQ0dnHdqsIVxjb3YaNbaIa/l3I4bsK5p/CqCFgR6XL5Sp8vtvMyHMIYGeLlwfSyN36AmijyTfy2nzyCcBS5BjG9WeZTHKNxMGhIje/W/zlO/PYatVWVSIbsUPmPiYYF916HY5OoorLNscWYV8GSZzbXdmXQJE6I/qespQ9DaemUUkJDM2FMgsZmWqIbBl3eUUDZ2CqHdSFPwuGelyLnMOLKcDJZtiWE55nj1Rxlzg3XJ3l9f+NQJMG6v2vXtOl8/CyJ2Z+uzA8Mwc+vmJW4qRjwGJsphutrDoEEn6AuSo3PLojxr879VhnNmUec0cabPKnh2TmxYJLFV7HRcvyCCprMyjz7ttK7Q=
  on:
    tags: true
    repo: quinnjs/cass
